// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"]!,
    // DIRECT_URL digunakan untuk Prisma Migrate (bypass PgBouncer)
    // Wajib di-set di Vercel agar migrations bisa jalan
    ...(process.env["DIRECT_URL"] && { directUrl: process.env["DIRECT_URL"] }),
  },
});
